url: https://testrepo.toogoodbruh.com   # with the https protocol
enforce_ssl: testrepo.toogoodbruh.com   # without any protocol

# For example, my configuration is this:
url: https://toogoodbruh.com
enforce_ssl: toogoodbruh.com
